#!/usr/bin/env bash
# Install nginx

apt-get update

apt-get install -y nginx

# Configure nginx to listen on port 80
# sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'

# Restart nginx
service nginx restart

# Create a temporary index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html
