#!/usr/bin/env bash
# Install nginx

apt-get update

apt-get install -y nginx

# Configure nginx to listen on port 80
# sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo ufw allow 'Nginx HTTP'

# Restart nginx
service nginx restart

# Create a temporary index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html


new_string="return 301 https:\/\/www.google.com;"
sudo sed -i "s/return 301 https:\/\/www.google.com;/$new_string/" /etc/nginx/sites-enabled/default

echo "This page doesn't exist" | sudo tee /var/www/html/custom_404.html
new_string="listen 80 default_server;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
