#!/usr/bin/env bash
# Blez Bro
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  http_front
        bind *:80
        mode http
        default_backend http_back
backend http_back
        balance roundrobin
        server 427881-web-01 100.25.45.86:80 check
        server 427881-web-02 52.91.183.224:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
