#!/bin/bash
# This script is used to install and configure the UFW firewall

sudo apt-get install ufw -y

sudo ufw reset

sudo ufw default deny incoming

sudo ufw allow 22/tcp

sudo ufw allow 443/tcp

sudo ufw allow 80/tcp

sudo ufw enable
